[package]
name = "cpa"
version = "0.0.1"
edition = "2018"

[dependencies]
askama = "0.12.1"
clap = { version = "4.4.6", features = ["derive"] }
regex = "1.10.2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
