default_language_version:
  python: python3

repos:
  #############################################################################
  # Misc
  #############################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict # Searches for merge conflict markers within files.
      - id: check-added-large-files # Blocks commits that add large files. Default limit is 500kB.
        # Can be configured with args, e.g., '--maxkb=1000' to change the limit.
        # exclude: 'your_dir/.*'
        # args: ['--maxkb=5000']
      - id: check-case-conflict # Identifies potential case-insensitive file name conflicts.
      - id: check-ast # Validates the syntax of Python files.
      - id: check-symlinks # Detects broken symlinks.
      - id: trailing-whitespace # Removes any trailing whitespace at the end of lines.
      - id: end-of-file-fixer # Ensures files end with a single newline or are empty.

  #############################################################################
  # JSON, TOML
  #############################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json # Validates JSON files to ensure they are properly formatted and syntactically correct.
        types: [json]

  #############################################################################
  # Shell
  #############################################################################
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt # Formats shell scripts to a standard convention using shfmt.
      - id: shellcheck # Lints shell scripts to identify syntax and usage errors, with a specified severity of 'warning'.
        args:
          - --severity=warning
  #############################################################################
  # CSS, Markdown, JavaScript, TypeScript, YAML style formatter
  #############################################################################
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier # An opinionated code formatter supporting multiple languages.
        name: prettier
        args: [--config, .ci/prettier.json, --write]
        types_or:
          - yaml
          - markdown
