name: integration

on:
  pull_request: # Start the job on all PRs
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install dependencies
        run: |
          sh ./test.sh
